# Generated by Django 3.2.7 on 2021-10-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.CharField(choices=[('Siyaset-Yazı', 'Siyaset-Yazı'), ('Siyaset-Haber', 'Siyaset-Haber'), ('Spor-Yazı', 'Spor-Yazı'), ('Spor-Haber', 'Spor-Haber'), ('Müzik', 'Müzik'), ('Sinema', 'Sinema'), ('Edebiyat', 'Edebiyat'), ('Sahne Sanatları', 'Sahne Sanatları'), ('Görsel Sanatlar', 'Görsel Sanatlar'), ('Gezi Notu', 'Gezi Notu'), ('Çeviri', 'Çeviri')], default='Siyaset-Yazı', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Makale Fotoğrafı'),
        ),
    ]
