# Generated by Django 3.2.7 on 2021-10-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20211029_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_category',
            new_name='makale_türü',
        ),
    ]
