# Generated by Django 3.2.7 on 2021-11-02 07:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_article_is_superarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='is_superarticle',
            field=models.BooleanField(default=0, verbose_name='Haftanın İçeriği Yap'),
        ),
    ]
