# Generated by Django 3.2.7 on 2021-11-08 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0017_auto_20211108_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Makale',
            new_name='Article',
        ),
    ]
